export const data = [
  {
    id: 1,
    memberId: "hong123",
    name: "홍길동",
    corporation: "마케팅팀",
    adMgmt: "전체",
    state: "활성",
    date: "2024-12-01",
  },
  {
    id: 2,
    memberId: "kim88",
    name: "김민수",
    corporation: "개발팀",
    adMgmt: "일부",
    state: "비활성",
    date: "2024-11-15",
  },
  {
    id: 3,
    memberId: "lee01",
    name: "이영희",
    corporation: "디자인팀",
    adMgmt: "전체",
    state: "활성",
    date: "2024-10-30",
  },
  {
    id: 4,
    memberId: "park007",
    name: "박재현",
    corporation: "인사팀",
    adMgmt: "일부",
    state: "비활성",
    date: "2024-09-20",
  },
  {
    id: 5,
    memberId: "choi55",
    name: "최서연",
    corporation: "영업팀",
    adMgmt: "전체",
    state: "활성",
    date: "2024-12-03",
  },
  {
    id: 6,
    memberId: "jang77",
    name: "장우진",
    corporation: "CS팀",
    adMgmt: "일부",
    state: "활성",
    date: "2024-10-10",
  },
  {
    id: 7,
    memberId: "yoon345",
    name: "윤하늘",
    corporation: "마케팅팀",
    adMgmt: "전체",
    state: "비활성",
    date: "2024-11-01",
  },
  {
    id: 8,
    memberId: "han901",
    name: "한지민",
    corporation: "기획팀",
    adMgmt: "일부",
    state: "활성",
    date: "2024-10-25",
  },
  {
    id: 9,
    memberId: "kang12",
    name: "강찬호",
    corporation: "디자인팀",
    adMgmt: "전체",
    state: "비활성",
    date: "2024-09-05",
  },
  {
    id: 10,
    memberId: "moonx",
    name: "문유라",
    corporation: "개발팀",
    adMgmt: "전체",
    state: "활성",
    date: "2024-12-05",
  },
];
